#!/bin/sh

echo "Updating and preparing"
sudo pacman -Syu

echo "Installing basic packages"
sudo pacman -S --noconfirm xorg-server xorg-xinit
sudo pacman -S --noconfirm slim
sudo pacman -S --noconfirm systemd
sudo pacman -S --noconfirm systemd-arch-units
sudo pacman -S --noconfirm openssh

echo "Installing wireless packages"
sudo pacman -S --noconfirm wpa_supplicant
sudo pacman -S --noconfirm netctl

echo "Installing fonts"
sudo pacman -S --noconfirm ttf-dejavu     # just a good font
sudo pacman -S --noconfirm terminus-font  # just a good font
sudo pacman -S --noconfirm ttf-symbola    # allow emoji

echo "Installing basic tools"
sudo pacman -S --noconfirm rsync
sudo pacman -S --noconfirm ntp
sudo pacman -S --noconfirm curl
sudo pacman -S --noconfirm xsel
sudo pacman -S --noconfirm unzip
sudo pacman -S --noconfirm imagemagick
sudo pacman -S --noconfirm slock
sudo pacman -S --noconfirm bash-completion
sudo pacman -S --noconfirm alsa-utils

echo "Installing stable browsers"
sudo pacman -S --noconfirm firefox

echo "Installing development tools"
sudo pacman -S --noconfirm base-devel
sudo pacman -S --noconfirm gvim
sudo pacman -S --noconfirm ruby
sudo pacman -S --noconfirm python
sudo pacman -S --noconfirm git
sudo pacman -S --noconfirm nodejs

echo "Installing awesome dependencies"
sudo pacman -S awesome feh vicious iptraf-ng

echo "installing specific packages for mordor"
sudo pacman -S xf86-video-ati
sudo pacman -S rxvt-unicode
sudo pacman -S alsa-oss
sudo pacman -S alsa-tools
sudo pacman -S xorg-xmodmap
sudo pacman -S xorg-rdb
sudo pacman -S xorg-xrandr
sudo pacman -S xf86-input-synaptics

echo "specific main libs"
sudo pacman -S openssl
sudo pacman -S readline

echo "specific development libs"
sudo pacman -S python2
sudo pacman -S python2-pip
sudo pacman -S bpython2
sudo pacman -S ruby
sudo pacman -S ghc

echo "specific development tools"
sudo pacman -S redis-server
sudo pacman -S mysql
sudo pacman -S sqlite

echo "Installing emacs and its dependencies"
sudo pacman -S --noconfirm emacs
sudo pacman -S --noconfirm aspell-pt

exit 0
