#!/bin/sh

echo "Updating and preparing"
sudo pacman -Syu

echo "Installing basic packages"
sudo pacman -S --noconfirm xorg-server xorg-xinit xorg-rdb xorg-xmodmap xorg-xrandr
sudo pacman -S --noconfirm slim
sudo pacman -S --noconfirm systemd
sudo pacman -S --noconfirm systemd-arch-units
sudo pacman -S --noconfirm openssh
sudo pacman -S --noconfirm sysstat

echo "Installing wireless packages"
sudo pacman -S --noconfirm wpa_supplicant
sudo pacman -S --noconfirm netctl

echo "installing specific packages for mordor"
sudo pacman -S --noconfirm rxvt-unicode
sudo pacman -S --noconfirm alsa-oss
sudo pacman -S --noconfirm alsa-tools
sudo pacman -S --noconfirm xf86-input-synaptics
sudo pacman -S --noconfirm linux-headers

echo "Installing fonts"
sudo pacman -S --noconfirm ttf-dejavu     # just a good font
sudo pacman -S --noconfirm terminus-font  # just a good font
sudo pacman -S --noconfirm ttf-symbola    # allow emoji

echo "Installing basic tools"
sudo pacman -S --noconfirm rsync
sudo pacman -S --noconfirm ntp
sudo pacman -S --noconfirm curl
sudo pacman -S --noconfirm xsel
sudo pacman -S --noconfirm unzip
sudo pacman -S --noconfirm imagemagick
sudo pacman -S --noconfirm slock
sudo pacman -S --noconfirm bash-completion
sudo pacman -S --noconfirm alsa-utils

echo "Installing stable browsers"
sudo pacman -S --noconfirm firefox

echo "Installing development tools"
sudo pacman -S --noconfirm base-devel
sudo pacman -S --noconfirm gvim
sudo pacman -S --noconfirm ruby
sudo pacman -S --noconfirm python
sudo pacman -S --noconfirm git
sudo pacman -S --noconfirm nodejs

echo "Installing awesome dependencies"
sudo pacman -S --noconfirm awesome feh vicious iptraf-ng

echo "Installing xfce4"
sudo pacman -S --noconfirm xfce4 xfce4-goodies

echo "specific main libs"
sudo pacman -S --noconfirm openssl
sudo pacman -S --noconfirm readline

echo "specific development libs"
sudo pacman -S --noconfirm python2
sudo pacman -S --noconfirm python2-pip
sudo pacman -S --noconfirm bpython2
sudo pacman -S --noconfirm ruby
sudo pacman -S --noconfirm ghc

echo "specific development tools"
sudo pacman -S --noconfirm redis-server
sudo pacman -S --noconfirm mysql
sudo pacman -S --noconfirm sqlite

echo "Installing emacs and its dependencies"
sudo pacman -S --noconfirm emacs
sudo pacman -S --noconfirm aspell-pt
sudo pacman -S --noconfirm aspell-en

echo "Installing Aura"
cd /tmp
curl aur.sh | bash -si aura-bin
cd -

echo "Installing packages from AUR"
sudo aura -A --noconfirm google-chrome-stable
sudo aura -A --noconfirm broadcom-wl-dkms

exit 0
