#!/bin/sh

echo "Updating and preparing"
sudo pacman -Syu

echo "Installing basic packages"
sudo pacman -S --noconfirm xorg-server xorg-xinit xorg-rdb xorg-xmodmap
sudo pacman -S --noconfirm slim
sudo pacman -S --noconfirm systemd
sudo pacman -S --noconfirm systemd-arch-units
sudo pacman -S --noconfirm openssh

echo "Installing wireless packages"
sudo pacman -S --noconfirm wpa_supplicant
sudo pacman -S --noconfirm netctl

echo "Installing fonts"
sudo pacman -S --noconfirm ttf-dejavu
sudo pacman -S --noconfirm terminus-font

echo "Installing basic tools"
sudo pacman -S --noconfirm rsync
sudo pacman -S --noconfirm ntp
sudo pacman -S --noconfirm curl
sudo pacman -S --noconfirm xsel
sudo pacman -S --noconfirm unzip
sudo pacman -S --noconfirm imagemagick
sudo pacman -S --noconfirm slock
sudo pacman -S --noconfirm bash-completion
sudo pacman -S --noconfirm alsa-utils

echo "Installing development tools"
sudo pacman -S --noconfirm base-devel
sudo pacman -S --noconfirm gvim
sudo pacman -S --noconfirm ruby
sudo pacman -S --noconfirm python
sudo pacman -S --noconfirm git
sudo pacman -S --noconfirm nodejs

echo "Installing awesome dependencies"
sudo pacman -S awesome feh vicious iptraf-ng

echo "Installing common softwares"
sudo pacman -S --noconfirm gimp
sudo pacman -S --noconfirm inkscape
sudo pacman -S --noconfirm pidgin
sudo pacman -S --noconfirm evince
sudo pacman -S --noconfirm aurvote
sudo pacman -S --noconfirm chromium
sudo pacman -S --noconfirm texlive-bin
sudo pacman -S --noconfirm vlc
sudo pacman -S --noconfirm dos2unix
sudo pacman -S --noconfirm steam
sudo pacman -S --noconfirm dropbox
sudo pacman -S --noconfirm shotwell

echo "Installing Aura"
$(sh <(curl aur.sh) -si aura-bin)

echo "Installing packages from AUR"
aura -A --noconfirm firefox-developer
aura -A --noconfirm google-chrome-stable
aura -A --noconfirm android-sdk-platform-tools

exit 0
