#!/bin/sh
case $1 in
  true)
      # go into powersave mode
      # NMI watchdog
      echo 0 > /proc/sys/kernel/watchdog
      # SD card reader
      # TODO test if sdcard mounted
      rmmod rts5139
      #VM writeback timeout
      echo 1500 > /proc/sys/vm/dirty_writeback_centisecs
      # SATA link power management
      for i in 0 1 2 3 4 5 ; do
              echo min_power>/sys/class/scsi_host/host${i}/link_power_management_policy
      done
      # Runtime PM for PCI Device
      for i in /sys/bus/pci/devices/*/power/control ; do
              echo auto > ${i}
      done
      # Runtime PM for USB Device
      for i in /sys/bus/usb/devices/*/power/control ; do
              echo auto > ${i}
      done
  ;;
  false)
      # go into AC mode
      echo 1 > /proc/sys/kernel/watchdog
      modprobe rts5139
      echo 60000 > /proc/sys/vm/dirty_writeback_centisecs
      for i in 0 1 2 3 4 5 ; do
              echo max_performance>/sys/class/scsi_host/host${i}/link_power_management_policy
      done
      for i in /sys/bus/pci/devices/*/power/control ; do
              echo on > ${i}
      done
  ;;
esac
exit 0
