#!/bin/sh

echo "Updating and preparing"
sudo pacman -Syu

echo "Installing basic packages"
sudo pacman -S xorg-server slim systemd systemd-arch-units

echo "Installing wireless packages"
sudo pacman -S wpa-actiond netcfg

echo "Installing fonts"
sudo pacman -S ttf-dejavu terminus-font

echo "Installing basic tools"
sudo pacman -S yaourt rsync curl xsel imagemagick slock bash-completion

echo "Installing stable browsers"
sudo pacman -S firefox opera google-chrome

echo "Installing development tools"
sudo pacman -S base-devel gvim ruby python git nodejs

echo "Installing common softwares"
sudo pacman -S gimp inkscape aurvote chromium texlive-bin vlc dos2unix steam dropbox

echo "Installing virt tools"
sudo pacman -S virt-manager
yaourt -S docker-lxc --noconfirm
yaourt -S lxc debootstrap dpkg --noconfirm

exit 0
