#!/bin/sh

echo "installing specific packages for mordor"
sudo pacman -S xf86-video-ati
sudo pacman -S rxvt-unicode
sudo pacman -S alsa-oss
sudo pacman -S alsa-tools
sudo pacman -S xorg-xmodmap
sudo pacman -S xorg-rdb
sudo pacman -S xorg-xrandr
sudo pacman -S xf86-input-synaptics

echo "specific main libs"
sudo pacman -S openssl
sudo pacman -S readline

echo "specific development libs"
sudo pacman -S python2
sudo pacman -S python2-pip
sudo pacman -S bpython2
sudo pacman -S ruby
sudo pacman -S ghc

echo "specific development tools"
sudo pacman -S redis-server
sudo pacman -S mysql
sudo pacman -S sqlite
